### ISSUE TITLE
add another disk to dashboard

### ISSUE THREAD

**Issue by johannmx** [oijkn/Docker-Raspberry-PI-Monitoring#12]
Hi! how can I add another disk to the dashboard? I have another mountpoint with fstype "ext4" but nothing shows up, thanks!

<img width="767" alt="Captura de pantalla 2022-01-19 093414" src="https://user-images.githubusercontent.com/63032152/150131635-01007c80-257b-4896-ba72-46cb4ffce10b.png">
<img width="1325" alt="Captura de pantalla 2022-01-19 093323" src="https://user-images.githubusercontent.com/63032152/150131747-229455da-1fa6-49e5-9230-befbe87786fb.png">

**Comment by oijkn** [comment]
Hi,

This dashboard only graph docker stuff not your host. For that you can use other dashboard from Grafana's community.

**Comment by johannmx** [comment]
Hi, ok thanks for the reply!
