### ISSUE TITLE
Unwritable directory

### ISSUE THREAD

**Issue by cyberralf83** [oijkn/Docker-Raspberry-PI-Monitoring#15]
The grafana container never starts for me and the log says: 
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later

I have changed the host path in /home/pi/graphs so it should have write access. 
I also tried to change the container's  permissions running: `docker exec monitoring-grafana sudo chown 472 /var/lib/grafana/ ` but i get. 
Error response from daemon: Container is restarting, wait until the container is running. Or  that the container is not running

**Comment by hellotinh03** [comment]
I'm having the same problem, have you found a fix yet?

**Comment by teemue** [comment]
Anyone?
