### ISSUE TITLE
network rpimonitor_default declared as external, but could not be found

### ISSUE THREAD

**Issue by getbiks** [oijkn/Docker-Raspberry-PI-Monitoring#18]
I am running Raspberry Pi ARM and I am getting this error when running docker-compose up -d
"network rpimonitor_default declared as external, but could not be found"

Any idea on how to fix it?

**Comment by oijkn** [comment]
Try to run this command before : `docker network create "rpimonitor_default"`

**Comment by Robert-K** [comment]
Ran into the same issue, this fixed it for me. Thanks!

**Comment by oijkn** [comment]
This issue has been inactive for some time. Please let me know if it's still relevant and need attention or I will close it.
