### ISSUE TITLE
cadvisor [Failed to create a Container Manager: mountpoint for cpu not found]

### ISSUE THREAD

**Issue by Just5KY** [oijkn/Docker-Raspberry-PI-Monitoring#2]
I'm using DietPi 32bit OS on my Raspberry Pi 4B 8B
I have added `cgroup_enable=memory cgroup_memory=1` in /boot/cmdline.txt
I followed all the steps mentioned, still running into this issue.

![image](https://user-images.githubusercontent.com/71321862/137593111-f2bc42e9-cdd7-4049-b73e-422dba668e69.png)

**Comment by oijkn** [comment]
I would say that something very weird with your `docker-ce` installation, try to follow those steps :

```sh
# Install some required packages first
sudo apt update
sudo apt install -y \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common

# Get the Docker signing key for packages
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -

# Add the Docker official repos
echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
     $(lsb_release -cs) stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list

# Install Docker
sudo apt update
sudo apt install -y --no-install-recommends \
    docker-ce \
    cgroupfs-mount
```

**Comment by oijkn** [comment]
I will try to rebuild cadvisor image with latest code and you try to ask dietpi's dev some help.

**Comment by Just5KY** [comment]
I switched back to RPi OS and everything is working. seems the issue is with DietPi.

**Comment by martadinata666** [comment]
Just add some comments, for consideration. The image `braingamer/cadvisor-arm:latest` used in stack was old enough, it fine if used on raspi os that based on buster, on newer OS like dietpi that based on bullseye it will throw errors like. Using newer image like `zcube/cadvisor` will work.

**Comment by oijkn** [comment]
@martadinata666 Thanks you for your feedback, I will try this new docker image and then update the stack. Perhaps I will add others metrics in the dashboard with this new version of cadvisor.
