### ISSUE TITLE
Access to GUI outside localhost

### ISSUE THREAD

**Issue by kanintesova** [oijkn/Docker-Raspberry-PI-Monitoring#20]
This is probably more of a docker thing. But it would be nice to get a hint how to connect to the GUI from outside localhost. I run a headless server. 

How can I connect to the docker internal IPs? I will try to ssh tunnel socks proxy and use firefox to check if it's possible to connect.

Thanks!

**Comment by martadinata666** [comment]
Like usual, nothing special http://Hostip:port

**Comment by kanintesova** [comment]
I must be missing something. Neither Grafana or Prometheus has been assigne IPs in docker :/

Thanks for the quick reply

**Comment by martadinata666** [comment]
As i don't know the of the grafana, by default it will be at hostip:3000, but maybe the grafana or prometheus not starting correctly you should check that'

**Comment by kanintesova** [comment]
Will check the logs

**Comment by kanintesova** [comment]
grafana:
    container_name: monitoring-grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied

But these files are in the container,

**Comment by kanintesova** [comment]
Ok I will need to start it with my user ID

**Comment by kanintesova** [comment]
As for Prometheus had to run as user also:
Omit where to look for the config file like so:

```
  prometheus:
    #command:
    # - '--config.file=/etc/prometheus/prometheus.yml'
    # - '--storage.tsdb.path=/prometheus'
    container_name: monitoring-prometheus
    user: root
```
Then point it at the mapped volume instead and put config file there:

```
volumes:
      # to be modified depending on your needs
      - /path/to/your/prometheus/data:/prometheus
      - /path/to/your/prometheus/config:/etc/prometheus/


```

Damn haha!

**Comment by oijkn** [comment]
I don't know if I understood everything but for Prometheus to work correctly you have to use the user `nobody` and for Grafana the user `472`.

Of course it is necessary to make a `chow -R <id> <directory>` of the directories where the data are located.

**Comment by C8opmBM** [comment]
I don't think the user/permissions are locked down to that specific user.
I run both graphana and prometheus with user 1000:1000 without issues
Important thing is to create the folders and configs with the same user before starting the container.

As for accessing grafana outside, you can use a reverse proxy on your subdomain.
I use caddy v2 with cloudflare plugin, this is my Caddyfile for grafana:

```
grafana.mydomain.com {
        reverse_proxy monitoring-grafana:3000
        tls {
                dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        }
}
```
