### ISSUE TITLE
Support for caddy v2

### ISSUE THREAD

**Issue by C8opmBM** [oijkn/Docker-Raspberry-PI-Monitoring#24]
Amazing project! I've been struggling to find an up-to-date dashboard for a while, and yours worked out of the box :)
Thanks!

Side request: maybe, if you find it useful, you can integrate caddy as a target. I would do it myself, but I can't figure it out.
Should be pretty straightforward for a dev, since caddy supports metrics with Prometheus.
https://caddyserver.com/docs/metrics
I tried it myself, but I get lost and all I get is empty tables.

**Comment by oijkn** [comment]
Hi, thanks for your message. The purpose of this stack is to monitor the Raspberry OS and the dockers running on it. I didn't know Caddy, it doesn't seem to meet the expectations of this observability project.

Sorry but I won't spend time on it, but if you need help or if I guide you, don't hesitate.
