### ISSUE TITLE
How to change default port 3000 ?

### ISSUE THREAD

**Issue by gaamaaresosa** [oijkn/Docker-Raspberry-PI-Monitoring#27]
Screen shots looking nice and I would like to try this in my RaspPi-4

My flask app is already running on port 3000, which I can't change.
How to change this grafana default port 3000 to something else?

Thanks in advance !

**Comment by oijkn** [comment]
You just have to change the port in the [docker-compose.yml](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/blob/main/docker-compose.yml#L12) file.

The example below will use port 8000 instead of 3000.

From:
```sh
    ports:
      - "3000:3000"
```

To:
```sh
    ports:
      - "8000:3000"
```

**Comment by gaamaaresosa** [comment]
> The example below will use port 8000 instead of 3000.

Thank you so much oijkn.
I will try this.

**Comment by oijkn** [comment]
You are welcome, can I close this issue?
