### ISSUE TITLE
High CPU on the cadvisor container

### ISSUE THREAD

**Issue by jslegers73** [oijkn/Docker-Raspberry-PI-Monitoring#34]
Hi,

I have installed this package and it is looking great. I do see a high CPU usage of cadvisor :

![image](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/assets/6212673/6df22d1a-aa06-4e65-95c2-9809d59641d3)

Is this normal?

It is running on a RP4 with 4Gb on a 64Bit Bookworm OS.

**Comment by oijkn** [comment]
Hello,

Thank you very much for highlighting this issue. After incorporating the new parameters into the cAdvisor command, the CPU usage has returned to normal.

Can you confirm ?

![image](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/assets/18188407/903fdd4a-3ce2-45d8-a77b-ee5725fd851b)

**Comment by jslegers73** [comment]
> Hello,
> 
> Thank you very much for highlighting this issue. After incorporating the new parameters into the cAdvisor command, the CPU usage has returned to normal.
> 
> Can you confirm ?
> 
> ![image](https://private-user-images.githubusercontent.com/18188407/320590957-903fdd4a-3ce2-45d8-a77b-ee5725fd851b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzU3NzIsIm5iZiI6MTcxMjY3NTQ3MiwicGF0aCI6Ii8xODE4ODQwNy8zMjA1OTA5NTctOTAzZmRkNGEtM2NlMi00NWQ4LWE3N2ItZWU1NzI1ZmQ4NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE1MTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NzFmNTU5MzQxNzRiY2QxZjQxMGZmMTVjZTJhNDAwMjc0MGJlZWVjMDgzMmYwZWUyNTc3ZjFhYjE4M2MzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SjT8Ih6Ae2Z_8zMLSPzLQE7oIR2Q_tzrB0IiNm3d6J0)

Hi,

Thanks for this. I have made the change and it helped.

![image](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/assets/6212673/f2829ece-45be-4192-9dcd-678f8b73664b)
