### ISSUE TITLE
Purge Prometheus database and reduce retention time

### ISSUE THREAD

**Issue by Stoobiedoo** [oijkn/Docker-Raspberry-PI-Monitoring#36]
I have this setup running on a normal Ubuntu server and the database has grown to several gigabytes in size.

How can I set the Prometheus database to only retain a certain time period of data and discard the rest?
Is there a way to manually purge the database entries? I'm hesitant to just delete the files in the
 /Docker-Raspberry-PI-Monitoring/prometheus/data folder.

**Comment by sierikov** [comment]
I'm not an expert on Prometheus, so please correct me if I'm mistaken. 

In the `docker-compose.yml` file, under the [`prometheus`](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/blob/main/docker-compose.yml#L69-L71) service, under the `commands` section, you can add the following options to ensure that the data for the last 15 days is always kept (for example) under 10 GB:
```yml
- '--storage.tsdb.retention.time=15d' # Retains data for 15 days
- '--storage.tsdb.retention.size=10GB' # Limits data retention to 10GB
```

Afterward, you will need to restart or recreate the service for the changes to take effect.

**Comment by Stoobiedoo** [comment]
That worked! Thanks for the answer.
