### ISSUE TITLE
Support for other filesystem?

### ISSUE THREAD

**Issue by froid-san** [oijkn/Docker-Raspberry-PI-Monitoring#4]
Anyway to add support for other file system like zfs for the grafana dashboard json?

unfortunately just by changing fstype=~"zfs" dos not seem to work on grafana dashboard.

**Comment by oijkn** [comment]
Sorry I don't have an environment with ZFS to adapt the dashboard settings.

**Comment by skyajal** [comment]
I recommend this enhancement request be closed as there is other options that can be added to grafana via other dashboards such as [this one](https://grafana.com/grafana/dashboards/15362) for example. I do use ZFS but not in an OS/boot capacity if that is the end goal here. I assume you want to just monitor the "data" ZFS pools/datasets that have been created. I think the goal of this dashboard focuses more on the host OS and Docker. If you want to monitor ZFS outside of that then you should consider adding an additional dashboard just for the ZFS stats to help keep this dashboard as clean as possible. Just my 2 cents.
