### ISSUE TITLE
ERROR: for grafana Cannot start service grafana:

### ISSUE THREAD

**Issue by Fooose** [oijkn/Docker-Raspberry-PI-Monitoring#5]
Hi,

Raspberry 4B 4GB

ERROR: for grafana Cannot start service grafana: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/path/to/your/grafana/grafana.ini" to rootfs at "/etc/grafana/grafana.ini" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: Encountered errors while bringing up the project.

![Bildschirmfoto 2021-11-03 um 16 26 50](https://user-images.githubusercontent.com/93667250/140091570-17047dff-ec08-4d80-94cc-7dedc6705c63.png)

**Comment by martadinata666** [comment]
```
 volumes:
      # to be modified depending on your needs
      - /path/to/your/grafana/data:/var/lib/grafana 
      - /path/to/your/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /path/to/your/grafana/provisioning:/etc/grafana/provisioning
```

As it stated modify as your need, if you don't modify `grafana.ini` just remote the line or comment it. Mandatory path just the first one.

**Comment by oijkn** [comment]
Why do you pull grafana docker image?

All you need is to clone this git repo and then use docker-compose up -d

The error message is clear, you are trying to mount a directory as file. So just rm it and create the grafana.ini file.

**Comment by Fooose** [comment]
thanks !
