### ISSUE TITLE
Removed containers are still visible 

### ISSUE THREAD

**Issue by nnachtegael** [oijkn/Docker-Raspberry-PI-Monitoring#9]
After removing containers they are still visible in the graphs even after docker system prune  - - all  - - volumes
I'm working on Ubuntu 21.10

**Comment by oijkn** [comment]
@nnachtegael try to download last version of Dashboard and tell me if it's better.

**Comment by nnachtegael** [comment]
the containers count is now OK thx
the removed containers are still present (more then one hour after removal) in the 'per container' graphs except for the 'Memory usage per container' graph

**Comment by nnachtegael** [comment]
the containers count is now OK thx
the removed containers are still present (more then one hour after removal) in the 'per container' graphs except for the 'Memory usage per container' graph

**Comment by nnachtegael** [comment]
the removed containers seems to disappear after a logout/login from the dashboard

**Comment by nnachtegael** [comment]
Every thing is now OK 
thx
